# ----------------------------------------------------------------- #
# List Section - These lists are to keep track of totems and tiers  #
#                                                                   #
# CreationTool Section - This is to customize the creation tool     #
#                                                                   #
# Debug Settings - For debug messages                               #
# ----------------------------------------------------------------- #
TotemList: []
TierList:
    - example
CreationTool:
    name: '&6&lCreation Tool'
    type: 'DIAMOND_AXE'
    lore:
        - ''
        - '&dUse to create totem spawner'
        - ''
        - '&7Right-click to set positions'
debug: false